### ISSUE TITLE
Could not get access to "https://docs.google.com/uc?export=download"

### ISSUE THREAD

**Issue by rtmaww** [fenchri/dsre-vae#1]
Hello. I'm running this code and when I try to make the data:
cd data/KB/
python make_data.py --data Freebase \
                    --train_file ../LANG/nyt10/nyt10_train.txt \
                    --val_file ../LANG/nyt10/nyt10_val.txt \
                    --test_file ../LANG/nyt10/nyt10_test.txt 

It could not get access to "https://docs.google.com/uc?export=download".
Can you share a link to directly download the data?

**Comment by fenchri** [comment]
Hi there,

You should be able to download it directly using the script since it calls `download_file_from_google_drive("1XYdeovP9XuRh_j83R7sSow6mwQhoUdwQ", "fb3m.tar.gz")`

Alternatively, you can install `gdown` and run `gdown --i 1XYdeovP9XuRh_j83R7sSow6mwQhoUdwQ`

The full link is:  https://drive.google.com/u/0/uc?id=1XYdeovP9XuRh_j83R7sSow6mwQhoUdwQ&export=download

**Comment by rtmaww** [comment]
Thank you. The codes still don't work when running train_embeds.sh. I think it's probably a GPU issue. (I'm using 3090-cuda10.1-cudnn7) May you share your GPU and cuda/cudnn version? 
![image](https://user-images.githubusercontent.com/32048818/125738574-31396a26-9816-4e74-ba69-1a4940028442.png)

**Comment by fenchri** [comment]
I see, yeah it looks like it. I used a single Nvidia V100 GPU for all experiments, cuda version 10.1.168 and cudnn 7.6.2, Pytorch 1.3.1 and python 3.7

Since it appears to be related to dglke, maybe you can also take a look here: https://github.com/awslabs/dgl-ke for potential issues. I didn't have a problem installing it with pip.

Hope this helps!
